//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/event.msg.
//

#ifndef __EVENT_M_H
#define __EVENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Event;
/**
 * Class generated from <tt>messages/event.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Event
 * {
 *     long eventID;
 *     bool toTrigger;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class Event : public ::omnetpp::cPacket
{
  protected:
    long eventID = 0;
    bool toTrigger = false;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const Event& other);

  protected:
    bool operator==(const Event&) = delete;

  public:
    Event(const char *name=nullptr, short kind=0);
    Event(const Event& other);
    virtual ~Event();
    Event& operator=(const Event& other);
    virtual Event *dup() const override {return new Event(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getEventID() const;
    virtual void setEventID(long eventID);

    virtual bool getToTrigger() const;
    virtual void setToTrigger(bool toTrigger);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Event& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Event& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Event *fromAnyPtr(any_ptr ptr) { return check_and_cast<Event*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __EVENT_M_H

