//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/IoTEvent.msg.
//

#ifndef __IOTEVENT_M_H
#define __IOTEVENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class IoTEvent;
/**
 * Class generated from <tt>messages/IoTEvent.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet IoTEvent
 * {
 *     long eventID;
 *     bool toTrigger;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class IoTEvent : public ::omnetpp::cPacket
{
  protected:
    long eventID = 0;
    bool toTrigger = false;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const IoTEvent& other);

  protected:
    bool operator==(const IoTEvent&) = delete;

  public:
    IoTEvent(const char *name=nullptr, short kind=0);
    IoTEvent(const IoTEvent& other);
    virtual ~IoTEvent();
    IoTEvent& operator=(const IoTEvent& other);
    virtual IoTEvent *dup() const override {return new IoTEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getEventID() const;
    virtual void setEventID(long eventID);

    virtual bool getToTrigger() const;
    virtual void setToTrigger(bool toTrigger);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IoTEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IoTEvent& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline IoTEvent *fromAnyPtr(any_ptr ptr) { return check_and_cast<IoTEvent*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOTEVENT_M_H

