//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/SimEvent.msg.
//

#ifndef __SIMEVENT_M_H
#define __SIMEVENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SimEvent;
/**
 * Class generated from <tt>messages/SimEvent.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet SimEvent
 * {
 *     long eventID;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class SimEvent : public ::omnetpp::cPacket
{
  protected:
    long eventID = 0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const SimEvent& other);

  protected:
    bool operator==(const SimEvent&) = delete;

  public:
    SimEvent(const char *name=nullptr, short kind=0);
    SimEvent(const SimEvent& other);
    virtual ~SimEvent();
    SimEvent& operator=(const SimEvent& other);
    virtual SimEvent *dup() const override {return new SimEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getEventID() const;
    virtual void setEventID(long eventID);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SimEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SimEvent& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SimEvent *fromAnyPtr(any_ptr ptr) { return check_and_cast<SimEvent*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SIMEVENT_M_H

